// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskAPI.Models
{
    public partial class Tasks
    {
        public Tasks()
        {
            TaskAssignments = new HashSet<TaskAssignments>();
            CreationDate = DateTime.UtcNow;
        }

        public int TaskId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? DueDate { get; set; }

        public virtual ICollection<TaskAssignments> TaskAssignments { get; set; }
    }
}